//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSP_Covid21.Models.ShopEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDRESS_SHIP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADDRESS_SHIP()
        {
            this.BILL = new HashSet<BILL>();
        }
    
        public int ADDRESSID { get; set; }
        public string USER { get; set; }
        public string FULLNAME { get; set; }
        public string PHONE { get; set; }
        public string CITY { get; set; }
        public string DISTRICT { get; set; }
        public string WARDS { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<bool> DEFAULT { get; set; }
        public Nullable<bool> ADDRESS_STATUS { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL> BILL { get; set; }
    }
}
