//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSP_Covid21.Models.ShopEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ww_BAUCUA_PLAYERDETAIL
    {
        public int PLAYERID { get; set; }
        public int ANIMALID { get; set; }
        public double BETS { get; set; }
    
        public virtual ww_BAUCUA_ANIMAL ww_BAUCUA_ANIMAL { get; set; }
        public virtual ww_BAUCUA_PLAYER ww_BAUCUA_PLAYER { get; set; }
    }
}
