//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSP_Covid21.Models.ShopEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ww_BAUCUA_ROOM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ww_BAUCUA_ROOM()
        {
            this.ww_BAUCUA_PLAYER = new HashSet<ww_BAUCUA_PLAYER>();
        }
    
        public int ROOMID { get; set; }
        public Nullable<int> AMOUNTPERSON { get; set; }
        public Nullable<bool> ROOMSTATUS { get; set; }
        public double MINBETS { get; set; }
        public string OWNER { get; set; }
        public string PASS { get; set; }
        public Nullable<int> DICE1 { get; set; }
        public Nullable<int> DICE2 { get; set; }
        public Nullable<int> DICE3 { get; set; }
    
        public virtual ww_BAUCUA_ACCOUNT ww_BAUCUA_ACCOUNT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ww_BAUCUA_PLAYER> ww_BAUCUA_PLAYER { get; set; }
    }
}
