//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSP_Covid21.Models.ShopEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ww_BAUCUA_ANIMAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ww_BAUCUA_ANIMAL()
        {
            this.ww_BAUCUA_PLAYERDETAIL = new HashSet<ww_BAUCUA_PLAYERDETAIL>();
        }
    
        public int ANIMALID { get; set; }
        public string ANIMALNAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ww_BAUCUA_PLAYERDETAIL> ww_BAUCUA_PLAYERDETAIL { get; set; }
    }
}
