//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSP_Covid21.Models.ShopEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ww_BAUCUA_PLAYER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ww_BAUCUA_PLAYER()
        {
            this.ww_BAUCUA_CHAT = new HashSet<ww_BAUCUA_CHAT>();
            this.ww_BAUCUA_PLAYERDETAIL = new HashSet<ww_BAUCUA_PLAYERDETAIL>();
        }
    
        public int PLAYERID { get; set; }
        public int ROOMID { get; set; }
        public string USERNAME { get; set; }
        public bool READY { get; set; }
        public Nullable<int> COLORID { get; set; }
        public Nullable<bool> DICE { get; set; }
    
        public virtual ww_BAUCUA_ACCOUNT ww_BAUCUA_ACCOUNT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ww_BAUCUA_CHAT> ww_BAUCUA_CHAT { get; set; }
        public virtual ww_BAUCUA_COLOR ww_BAUCUA_COLOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ww_BAUCUA_PLAYERDETAIL> ww_BAUCUA_PLAYERDETAIL { get; set; }
        public virtual ww_BAUCUA_ROOM ww_BAUCUA_ROOM { get; set; }
    }
}
