//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSP_Covid21.Models.ShopEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ww_BAUCUA_CHAT
    {
        public int CHATID { get; set; }
        public Nullable<int> PLAYERID { get; set; }
        public string TEXTCHAT { get; set; }
        public int NUMBERVIEWERS { get; set; }
    
        public virtual ww_BAUCUA_PLAYER ww_BAUCUA_PLAYER { get; set; }
    }
}
