//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSP_Covid21.Models.ShopEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ww_BillDetail
    {
        public int BillId { get; set; }
        public int ProductId { get; set; }
        public double Amount { get; set; }
    
        public virtual ww_Bill ww_Bill { get; set; }
        public virtual ww_Product ww_Product { get; set; }
    }
}
