//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSP_Covid21.Models.ShopEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ww_BAUCUA_ACCOUNT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ww_BAUCUA_ACCOUNT()
        {
            this.ww_BAUCUA_ROOM = new HashSet<ww_BAUCUA_ROOM>();
            this.ww_BAUCUA_PLAYER = new HashSet<ww_BAUCUA_PLAYER>();
        }
    
        public string ACCOUNTNAME { get; set; }
        public string USERNAME { get; set; }
        public string PASS { get; set; }
        public double MONEY { get; set; }
        public Nullable<bool> AC_STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ww_BAUCUA_ROOM> ww_BAUCUA_ROOM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ww_BAUCUA_PLAYER> ww_BAUCUA_PLAYER { get; set; }
    }
}
