//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSP_Covid21.Models.ShopEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.ACCOUNTLIKEs = new HashSet<ACCOUNTLIKE>();
            this.BILLDETAILs = new HashSet<BILLDETAIL>();
            this.COMMENTs = new HashSet<COMMENT>();
            this.CONFIGDETAILs = new HashSet<CONFIGDETAIL>();
            this.RATINGPRODUCTs = new HashSet<RATINGPRODUCT>();
            this.VIEWNUMBERs = new HashSet<VIEWNUMBER>();
            this.CARTs = new HashSet<CART>();
        }
    
        public int PRODUCTID { get; set; }
        public string PRODUCTNAME { get; set; }
        public Nullable<int> BRANDID { get; set; }
        public Nullable<int> PRODUCTTYPEID { get; set; }
        public string MAINPIC { get; set; }
        public string PIC1 { get; set; }
        public string PIC2 { get; set; }
        public string PIC3 { get; set; }
        public string PIC4 { get; set; }
        public Nullable<bool> STATUSPRODUCT { get; set; }
        public Nullable<int> PRODUCTPRICE { get; set; }
        public Nullable<int> PRODUCTAMOUNT { get; set; }
        public string DECRIPTION { get; set; }
        public Nullable<System.DateTime> DATEADD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCOUNTLIKE> ACCOUNTLIKEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILLDETAIL> BILLDETAILs { get; set; }
        public virtual BRAND BRAND { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENT> COMMENTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONFIGDETAIL> CONFIGDETAILs { get; set; }
        public virtual PRODUCTTYPE PRODUCTTYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RATINGPRODUCT> RATINGPRODUCTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIEWNUMBER> VIEWNUMBERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CART> CARTs { get; set; }
    }
}
