//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ACCOUNT
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ACCOUNT()
    {
        this.ACCOUNTLIKEs = new HashSet<ACCOUNTLIKE>();
        this.CARTs = new HashSet<CART>();
        this.COMMENTs = new HashSet<COMMENT>();
        this.VOCHERDETAILs = new HashSet<VOCHERDETAIL>();
        this.RATINGPRODUCTs = new HashSet<RATINGPRODUCT>();
        this.VIEWNUMBERs = new HashSet<VIEWNUMBER>();
    }

    public string USER { get; set; }
    public string PASSWORD { get; set; }
    public string FULLNAME { get; set; }
    public Nullable<bool> STATUSACCOUNT { get; set; }
    public string PHONENUMBER { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ACCOUNTLIKE> ACCOUNTLIKEs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CART> CARTs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<COMMENT> COMMENTs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<VOCHERDETAIL> VOCHERDETAILs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<RATINGPRODUCT> RATINGPRODUCTs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<VIEWNUMBER> VIEWNUMBERs { get; set; }
}

public partial class ACCOUNT_ADMIN
{
    public string USER { get; set; }
    public string PASSWORD { get; set; }
    public string FULLNAME { get; set; }
    public Nullable<bool> STATUSACCOUNT { get; set; }
}

public partial class ACCOUNTLIKE
{
    public string USER { get; set; }
    public int PRODUCTID { get; set; }
    public Nullable<System.DateTime> DATELIKE { get; set; }

    public virtual ACCOUNT ACCOUNT { get; set; }
    public virtual PRODUCT PRODUCT { get; set; }
}

public partial class BILL
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public BILL()
    {
        this.BILLDETAILs = new HashSet<BILLDETAIL>();
    }

    public int BILLID { get; set; }
    public string USER { get; set; }
    public string ADDRESS { get; set; }
    public string PHONENUMBERRECIVE { get; set; }
    public Nullable<System.DateTime> DATECREATE { get; set; }
    public Nullable<int> VOUCHERID { get; set; }

    public virtual VOUCHER VOUCHER { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<BILLDETAIL> BILLDETAILs { get; set; }
}

public partial class BILLDETAIL
{
    public int BILLID { get; set; }
    public int PRODUCTID { get; set; }
    public Nullable<int> AMOUNT { get; set; }

    public virtual BILL BILL { get; set; }
    public virtual PRODUCT PRODUCT { get; set; }
}

public partial class BRAND
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public BRAND()
    {
        this.PRODUCTs = new HashSet<PRODUCT>();
        this.TEMPPRODUCTs = new HashSet<TEMPPRODUCT>();
    }

    public int BRANDID { get; set; }
    public string BRANDNAME { get; set; }
    public Nullable<bool> STATUSBRAND { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PRODUCT> PRODUCTs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TEMPPRODUCT> TEMPPRODUCTs { get; set; }
}

public partial class CART
{
    public string USER { get; set; }
    public int PRODUCTID { get; set; }
    public Nullable<int> AMOUNT { get; set; }

    public virtual ACCOUNT ACCOUNT { get; set; }
    public virtual PRODUCT PRODUCT { get; set; }
}

public partial class COMMENT
{
    public int COMMENTID { get; set; }
    public Nullable<int> PRODUCTID { get; set; }
    public string USER { get; set; }
    public string COMMENTTEXT { get; set; }

    public virtual ACCOUNT ACCOUNT { get; set; }
    public virtual PRODUCT PRODUCT { get; set; }
}

public partial class CONFIG
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CONFIG()
    {
        this.CONFIGDETAILs = new HashSet<CONFIGDETAIL>();
    }

    public string CONFIGNAME { get; set; }
    public string DECRIPTIONCONFIGNAME { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CONFIGDETAIL> CONFIGDETAILs { get; set; }
}

public partial class CONFIGDETAIL
{
    public int PRODUCTID { get; set; }
    public string CONFIGNAME { get; set; }
    public string INFORMATION { get; set; }

    public virtual CONFIG CONFIG { get; set; }
    public virtual PRODUCT PRODUCT { get; set; }
}

public partial class PRODUCT
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PRODUCT()
    {
        this.ACCOUNTLIKEs = new HashSet<ACCOUNTLIKE>();
        this.BILLDETAILs = new HashSet<BILLDETAIL>();
        this.CARTs = new HashSet<CART>();
        this.COMMENTs = new HashSet<COMMENT>();
        this.CONFIGDETAILs = new HashSet<CONFIGDETAIL>();
        this.RATINGPRODUCTs = new HashSet<RATINGPRODUCT>();
        this.VIEWNUMBERs = new HashSet<VIEWNUMBER>();
    }

    public int PRODUCTID { get; set; }
    public string PRODUCTNAME { get; set; }
    public Nullable<int> BRANDID { get; set; }
    public Nullable<int> PRODUCTTYPEID { get; set; }
    public string MAINPIC { get; set; }
    public string PIC1 { get; set; }
    public string PIC2 { get; set; }
    public string PIC3 { get; set; }
    public string PIC4 { get; set; }
    public Nullable<bool> STATUSPRODUCT { get; set; }
    public Nullable<int> PRODUCTPRICE { get; set; }
    public Nullable<int> PRODUCTAMOUNT { get; set; }
    public string DECRIPTION { get; set; }
    public Nullable<System.DateTime> DATEADD { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ACCOUNTLIKE> ACCOUNTLIKEs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<BILLDETAIL> BILLDETAILs { get; set; }
    public virtual BRAND BRAND { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CART> CARTs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<COMMENT> COMMENTs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CONFIGDETAIL> CONFIGDETAILs { get; set; }
    public virtual PRODUCTTYPE PRODUCTTYPE { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<RATINGPRODUCT> RATINGPRODUCTs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<VIEWNUMBER> VIEWNUMBERs { get; set; }
}

public partial class PRODUCTTYPE
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PRODUCTTYPE()
    {
        this.PRODUCTs = new HashSet<PRODUCT>();
        this.TEMPPRODUCTs = new HashSet<TEMPPRODUCT>();
    }

    public int PRODUCTTYPEID { get; set; }
    public string PRODUCTTYPENAME { get; set; }
    public Nullable<bool> STATUSPRODUCTTYPE { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PRODUCT> PRODUCTs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TEMPPRODUCT> TEMPPRODUCTs { get; set; }
}

public partial class RATINGPRODUCT
{
    public string USER { get; set; }
    public int PRODUCTID { get; set; }
    public Nullable<double> RATE { get; set; }

    public virtual ACCOUNT ACCOUNT { get; set; }
    public virtual PRODUCT PRODUCT { get; set; }
}

public partial class TEMPPRODUCT
{
    public int PRODUCTTYPEID { get; set; }
    public int BRANDID { get; set; }
    public Nullable<bool> TEMPPRODUCTSTATUS { get; set; }

    public virtual BRAND BRAND { get; set; }
    public virtual PRODUCTTYPE PRODUCTTYPE { get; set; }
}

public partial class VIEWNUMBER
{
    public string USER { get; set; }
    public int PRODUCTID { get; set; }
    public Nullable<System.DateTime> DATESEEN { get; set; }

    public virtual ACCOUNT ACCOUNT { get; set; }
    public virtual PRODUCT PRODUCT { get; set; }
}

public partial class VOCHERDETAIL
{
    public int VOUCHERID { get; set; }
    public string USER { get; set; }
    public Nullable<System.DateTime> DATEENDTIRE { get; set; }

    public virtual ACCOUNT ACCOUNT { get; set; }
    public virtual VOUCHER VOUCHER { get; set; }
}

public partial class VOUCHER
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public VOUCHER()
    {
        this.BILLs = new HashSet<BILL>();
        this.VOCHERDETAILs = new HashSet<VOCHERDETAIL>();
    }

    public int VOUCHERID { get; set; }
    public string DECRIPTIONVOUCHER { get; set; }
    public Nullable<System.DateTime> DATEENDTIRE { get; set; }
    public Nullable<bool> STATUSVOUCHER { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<BILL> BILLs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<VOCHERDETAIL> VOCHERDETAILs { get; set; }
}
