//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSP_Covid21.Models.ShopEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPPRODUCT
    {
        public int PRODUCTTYPEID { get; set; }
        public int BRANDID { get; set; }
        public Nullable<bool> TEMPPRODUCTSTATUS { get; set; }
    
        public virtual BRAND BRAND { get; set; }
        public virtual PRODUCTTYPE PRODUCTTYPE { get; set; }
    }
}
